export enum DeckColor {
	AmberAmethyst = "Amber / Amethyst",
	AmberEmerald = "Amber / Emerald",
	AmberRuby = "Amber / Ruby",
	AmberSapphire = "Amber / Sapphire",
	AmberSteel = "Amber / Steel",
	AmethystEmerald = "Amethyst / Emerald",
	AmethystRuby = "Amethyst / Ruby",
	AmethystSapphire = "Amethyst / Sapphire",
	AmethystSteel = "Amethyst / Steel",
	EmeraldRuby = "Emerald / Ruby",
	EmeraldSapphire = "Emerald / Sapphire",
	EmeraldSteel = "Emerald / Steel",
	RubySapphire = "Ruby / Sapphire",
	RubySteel = "Ruby / Steel",
	SapphireSteel = "Sapphire / Steel",
}